name: farmeragriapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  boxes: ^1.0.2
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  file_picker: ^9.2.1
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_localization: ^0.3.3
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.12
  getwidget: ^6.0.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: 0.20.2
  jwt_decoder: ^2.0.1
  open_file: ^3.5.10
  shared_preferences: ^2.5.3
  standard_searchbar: ^2.1.1
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

flutter_icons:
  android: true
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/Dearo Agro.png"
